version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'stravaapi'
      POSTGRES_PASSWORD: 'stravaapi'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server #--requirepass yourpassword
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s
    command: sh -c "rake db:create && rake db:migrate && rake db:seed && puma -C config/puma.rb"
    ports:
      - '3001:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  # sidekiq:
  #   depends_on:
  #     - 'postgres'
  #     - 'redis'
  #   build: .
  #   command: sidekiq -C config/sidekiq.yml.erb
  #   volumes:
  #     - '.:/app'
  #   env_file:
  #     - '.env'

volumes:
  redis:
  postgres:
