default: &default
  adapter: postgis
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: 5
  timeout: 5000
  user: <%= ENV.fetch('DB_USER', 'stravaapi') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'stravaapi') %>

development:
  <<: *default
  database: stravaapi_dev

test:
  <<: *default
  database: stravaapi_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'stravaapi') %>
