# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  pool: 5
  timeout: 5000
  user: <%= ENV.fetch('DB_USER', 'straavapi') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'straavapi') %>

development:
  <<: *default
  database: stravaapi_dev

test:
  <<: *default
  database: stravaapi_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'straavapi') %>
